language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_b9113630a4c4_key -iv $encrypted_b9113630a4c4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa 
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ~/ssh_config ~/.ssh/config
- git config --global user.name 'snowdream'
- git config --global user.email yanghui1986527@gmail.com 
install:
- npm install hexo -g
- npm install
script:
- hexo clean
- hexo d -g
